# Generated by Django 4.2.4 on 2023-08-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(choices=[(False, 'Не принят'), (True, 'Принят')], default=False, verbose_name='Принят'),
        ),
    ]
